### ISSUE TITLE
Number keys to switch weapons

### ISSUE THREAD

**Issue by sadisof** [CircuitDev192/Game3#21]
Since we're going for a primary/secondary system, we could just do 1 and 2 for now, if that's easier.

**Comment by Rhett-Fereday** [comment]
Because we only have primary, secondary, and melee it only takes a single movement of the scroll wheel to go from where you are to where you want to be. I think that negates the need for number switching for weapons. However, there will be a number of consumables which will need to be cycled through which means the scroll wheel won't be sufficient. But if we use number keys then we need a method of displaying which numbers do what in the UI which could get cluttered. See issue #42 for an alternate solution that I will be implementing.

**Comment by sadisof** [comment]
get owned punk i'm doing it myself
